# --- !Ups

create table SCHEME (
    EMPREF VARCHAR NOT NULL PRIMARY KEY,
    TERMINATION_DATE DATE NULL
);

CREATE TABLE LEVY_DECLARATION(
  YEAR INTEGER NOT NULL,
  MONTH INTEGER NOT NULL,
  AMOUNT NUMERIC NOT NULL,
  EMPREF VARCHAR NOT NULL,
  PRIMARY KEY (YEAR, MONTH, EMPREF),
  FOREIGN KEY (EMPREF) REFERENCES SCHEME(EMPREF)
);

CREATE TABLE ACCESS_TOKEN(
  ACCESS_TOKEN VARCHAR NOT NULL PRIMARY KEY,
  SCOPE VARCHAR NOT NULL,
  EXPIRES_AT DATE NOT NULL,
  CREATED_AT DATE NOT NULL
);

# --- !Downs

DROP TABLE LEVY_DECLARATION;
DROP TABLE SCHEME;
DROP TABLE ACCESS_TOKEN;
