# --- !Ups

create table "ORGANISATION" ("UTR" VARCHAR NOT NULL PRIMARY KEY, NAME VARCHAR NOT NULL);
create table "SCHEME" (
    "EMPREF" VARCHAR NOT NULL PRIMARY KEY,
    "UTR" VARCHAR NULL,
     FOREIGN KEY (UTR) REFERENCES ORGANISATION(UTR)
);

CREATE TABLE LEVY_DECLARATION(
  YEAR INTEGER NOT NULL,
  MONTH INTEGER NOT NULL,
  AMOUNT NUMERIC NOT NULL,
  EMPREF VARCHAR NOT NULL,
  PRIMARY KEY (YEAR, MONTH, EMPREF),
  FOREIGN KEY (EMPREF) REFERENCES SCHEME(EMPREF)
);

CREATE TABLE DAS_USER (
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL
);



# --- !Downs

drop table "SCHEME";
drop table "ORGANISATION";
DROP TABLE LEVY_DECLARATION;
DROP TABLE DAS_USER;