# --- !Ups

CREATE TABLE LEVY_DECLARATION(
  YEAR INTEGER NOT NULL,
  MONTH INTEGER NOT NULL,
  AMOUNT NUMERIC NOT NULL,
  EMPREF VARCHAR NOT NULL,
  FOREIGN KEY (EMPREF) REFERENCES SCHEME(EMPREF)
);

# --- !Downs

DROP TABLE LEVY_DECLARATION;
