# --- !Ups


CREATE TABLE GATEWAY_USER(
  ID INTEGER NOT NULL PRIMARY KEY,
  USERNAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL
);

INSERT INTO GATEWAY_USER (ID, USERNAME, PASSWORD) VALUES (1, 'gateway1', 'password');

# --- !Downs

DROP TABLE GATEWAY_USER;